Use -target-feature for MTE
Instead of setting -march, use clang's -target-feature functionality
to enable MTE. Some projects set -march which may conflict with MTE's
usage. Using -target-feature to enable MTE removes any clang command
line ordering issues.

History:
* Originally submitted as c022b4677d7bc7a43b820ed982bcbc56189032ae
* reverted in b9a7d1268aa2294019004f0ef4cecdfe3963b74d due to
  bug 371029823
* Prematurely resubmitted as 027f93361a83402c5b09fc800a559b32267166c4
  and then subsequently reverted in
  5c4d0a3316b8c5f877e81d24ebb1008f02334daf as the fix for bug 371029823
  had not yet landed.

Fixes the following compile failures on _fullmte builds:
  vendor/google/services/LyricCameraHAL/src/lyric/api/algo/data_types/local_tone_mapping_data_v1.cc
  vendor/google/services/LyricCameraHAL/src/lyric/api/algo/data_types/local_tone_mapping_data_v1.cc:209:34: error: always_inline function 'vpaddq_f16' requires target feature 'fullfp16', but would be inlined into function 'GridMeanNeon' that is compiled without support for 'fullfp16'
    209 |       vmulq_f16(norm, vpaddq_f16(vpaddq_f16(slope_bias[0], slope_bias[1]),
        |                                  ^
  vendor/google/services/LyricCameraHAL/src/lyric/api/algo/data_types/local_tone_mapping_data_v1.cc:210:34: error: always_inline function 'vpaddq_f16' requires target feature 'fullfp16', but would be inlined into function 'GridMeanNeon' that is compiled without support for 'fullfp16'
    210 |                                  vpaddq_f16(slope_bias[2], slope_bias[3])));

Bug: 366222162
Test: compiles and boots
Change-Id: Ib7ef224dc38b07c69dbf1e474cc6d225c5ae220a